### ISSUE TITLE
The POM for getalp:ufsac:jar:1.0-SNAPSHOT is missing, no dependency information available

### ISSUE THREAD

**Issue by sophiaabraham96** [getalp/disambiguate#1]
When attempting to install UFSAC and running the debug log, find this error appearing, can not find the POM directly either

**Comment by loic-vial** [comment]
Normally, if you've installed UFSAC correctly, it should be located in your local Maven repository in `~/.m2/repository/getalp/ufsac`, and it is automatically found when compiling.

Can you run (or re-run) the following commands, and if it still does not work, report the output :
- `git clone https://github.com/getalp/UFSAC`
- `cd UFSAC`
- `./java/install.sh`

**Comment by sophiaabraham96** [comment]
It is fine now! Thank you so much for your help! :)
