### ISSUE TITLE
Training model : IndexError: list index out of range

### ISSUE THREAD

**Issue by YangtaoWANG95** [getalp/disambiguate#10]
When I trained the model, I had a strange **error each time at the end of the first batch**. Here is the details of the error: 

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/train.py", line 101, in <module>
    main()
  File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/train.py", line 97, in main
    trainer.train()
  File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/trainer.py", line 250, in train
    dev_losses, dev_wsd, dev_bleu = self.test_on_dev(dev_samples, model)
  File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/trainer.py", line 329, in test_on_dev
    loss = self.get_loss_metrics(dev_samples, model)
  File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/trainer.py", line 341, in get_loss_metrics
    batch_x, batch_y, batch_z, batch_tt, actual_batch_size, reached_eof = read_batch_from_samples(dev_samples, self.batch_size, self.token_per_batch, current_index, model.config.data_config.input_features, model.config.data_config.output_features, model.config.data_config.output_translations, model.config.data_config.output_translation_features, model.config.data_config.input_clear_text, model.config.data_config.output_translation_clear_text)
  File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/common.py", line 236, in read_batch_from_samples
    pad_batch_y(batch_y)
  File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/common.py", line 164, in pad_batch_y
    batch_y[i] = pad_sequence(batch_y[i], batch_first=True)
  File "/usr/lib/python3.7/site-packages/torch/nn/utils/rnn.py", line 376, in pad_sequence
    max_size = sequences[0].size()
**IndexError: list index out of range**

**My environment** is as the following : 
Linux Manjaro distribution
Python 3.8 (I modify the the python launch script to force use python3.7 like this : PYTHONPATH="$(dirname "$0")":$PYTHONPATH python3.7 -u -m "$@") 
Cuda 10.1 

Here is the **command** that I use to prepare the data, train the model : 
./prepare_data.sh --data_path ./data/ --train ./ufsac-public-1.0.0/semcor.xml  --input_clear_text true (./data is the pre-trained model model_wsd_train_sc_wngt_dev_random4000_clear_compress_bert_large_cased_transformer_2048.zip )

./train.sh  --data_path ./data/ --model_path ./trained --batch_size 50 --input_bert_model bert-base-uncased

I don't know if it is a problem of lack of dependency or mis intall a version of dependency, or there is something wrong with my training command.

**Comment by loic-vial** [comment]
Hi,

I think that you are trying to *use* a pre-trained model, and not *train* a new model by yourself.

If you want to use the pre-trained model given in the `model_wsd_train_sc_wngt_dev_random4000_clear_compress_bert_large_cased_transformer_2048.zip` archive, you do not need to call `prepare_data.sh` or `train.sh`, because the model is already trained.

However, if you want to train a new model by yourself, the `--data_path` argument of the `prepare_data.sh` script should point to a new directory.

**Comment by YangtaoWANG95** [comment]
I tried to point out a new directory, but the same error still happen. 
Here is the command that I used : 
./prepare_data.sh --data_path ./new_data --train ./ufsac-public-1.0.0/semcor.xml --input_clear_text true 

./train.sh --data_path ./new_data --model_path ./trained --batch_size 50 --input_bert_model bert-base-cased

where ./new_data is an empty directory. 
and the error is : 

Ensemble 0 - Epoch 0 - Batch 0 - Sample 0 - Total Batch 0 - Total Sample 0 - Skipped 0 batch - Train losses = [None] - Dev losses = [None] - Dev wsd = [None] - Dev bleu = None
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/train.py", line 101, in <module>
    main()
  File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/train.py", line 97, in main
    trainer.train()
  File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/trainer.py", line 250, in train
    dev_losses, dev_wsd, dev_bleu = self.test_on_dev(dev_samples, model)
  File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/trainer.py", line 329, in test_on_dev
    loss = self.get_loss_metrics(dev_samples, model)
  File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/trainer.py", line 341, in get_loss_metrics
    batch_x, batch_y, batch_z, batch_tt, actual_batch_size, reached_eof = read_batch_from_samples(dev_samples, self.batch_size, self.token_per_batch, current_index, model.config.data_config.input_features, model.config.data_config.output_features, model.config.data_config.output_translations, model.config.data_config.output_translation_features, model.config.data_config.input_clear_text, model.config.data_config.output_translation_clear_text)
  File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/common.py", line 235, in read_batch_from_samples
    pad_batch_y(batch_y)
  File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/common.py", line 163, in pad_batch_y
    batch_y[i] = pad_sequence(batch_y[i], batch_first=True)
  File "/usr/lib/python3.7/site-packages/torch/nn/utils/rnn.py", line 376, in pad_sequence
    max_size = sequences[0].size()
IndexError: list index out of range

**Comment by loic-vial** [comment]
Ok. Can you provide the output of the `prepare_data.sh` and also the whole output of the `train.sh` ?

**Comment by YangtaoWANG95** [comment]
This is the whole output of the **prepare_data.sh** and **train.sh.** 
**If this is still not enough, can you give me your office address, I can directly find you at your office at Grenoble?** 

**[wangyangtao@wangyangtao-pc disambiguate]$ ./prepare_data.sh --data_path ./new_data --train ./corpus/semcor.xml --input_clear_text true**
Arguments:
    --help (default value) = false
    --data_path = ./new_data
    --train = [./corpus/semcor.xml]
    --dev (default value) = []
    --dev_from_train (default value) = 0
    --corpus_format (default value) = xml
    --txt_corpus_features (default value) = [null]
    --input_features (default value) = [surface_form]
    --input_embeddings (default value) = [null]
    --input_vocabulary (default value) = [null]
    --input_vocabulary_limit (default value) = -1
    --input_clear_text = [true]
    --output_features (default value) = [wn30_key]
    --output_feature_vocabulary_limit (default value) = -1
    --truncate_line_length (default value) = 80
    --exclude_line_length (default value) = 150
    --line_length_tokenizer (default value) = null
    --lowercase (default value) = false
    --filter_lemma (default value) = true
    --uniform_dash (default value) = false
    --sense_compression_hypernyms (default value) = true
    --sense_compression_instance_hypernyms (default value) = false
    --sense_compression_antonyms (default value) = false
    --sense_compression_file (default value) = 
    --add_wordkey_from_sensekey (default value) = false
    --add_monosemics (default value) = false
    --remove_monosemics (default value) = false
    --remove_duplicates (default value) = true
Extracting sentences from corpus ./corpus/semcor.xml
Cleaning sentences
Cleaning sentences
Building vocabulary
Building vocabulary
Filtering sentences without feature
Removing duplicate sentences
Removing empty parallel sentences
Removing empty parallel sentences
Writing corpus ./new_data/train
Writing corpus ./new_data/dev

**[wangyangtao@wangyangtao-pc disambiguate]$ ./train.sh --data_path ./new_data --model_path ./trained --batch_size 50 --input_bert_model bert-base-cased**
Command line arguments:
{'adam_beta1': 0.9,
 'adam_beta2': 0.999,
 'adam_eps': 1e-08,
 'batch_size': 50,
 'data_path': './new_data',
 'encoder_lstm_dropout': None,
 'encoder_lstm_hidden_size': None,
 'encoder_lstm_layers': None,
 'encoder_transformer_dropout': None,
 'encoder_transformer_heads': None,
 'encoder_transformer_hidden_size': None,
 'encoder_transformer_layers': None,
 'encoder_transformer_positional_encoding': None,
 'encoder_transformer_scale_embeddings': None,
 'encoder_type': None,
 'ensemble_count': 8,
 'epoch_count': 40,
 'eval_frequency': 4000,
 'input_auto_model': None,
 'input_auto_path': None,
 'input_bert_model': ['bert-base-cased'],
 'input_dropout_rate': None,
 'input_elmo_model': None,
 'input_embeddings_size': None,
 'input_embeddings_tokenize_model': None,
 'input_linear_size': None,
 'input_resize': None,
 'input_word_dropout_rate': None,
 'lr_scheduler': 'fixed',
 'lr_scheduler_fixed_lr': 0.0001,
 'lr_scheduler_noam_model_size': 512,
 'lr_scheduler_noam_warmup': 6000,
 'model_path': './trained',
 'optimizer': 'adam',
 'reset': False,
 'save_best_loss': False,
 'save_every_epoch': False,
 'token_per_batch': 8000,
 'update_frequency': 1,
 'warmup_batch_count': 10}
Loading config and embeddings
GPU is available: True
Creating model
Random seed is 2407306634622226975
Config is: 
{'decoder_translation_scale_embeddings': True,
 'decoder_translation_share_embeddings': False,
 'decoder_translation_share_encoder_embeddings': False,
 'decoder_translation_tokenizer_bert': None,
 'decoder_translation_transformer_dropout': 0.1,
 'decoder_translation_transformer_heads': 8,
 'decoder_translation_transformer_hidden_size': 512,
 'decoder_translation_transformer_layers': 6,
 'encoder_lstm_dropout': 0.5,
 'encoder_lstm_hidden_size': 1000,
 'encoder_lstm_layers': 1,
 'encoder_transformer_dropout': 0.1,
 'encoder_transformer_heads': 8,
 'encoder_transformer_hidden_size': 512,
 'encoder_transformer_layers': 6,
 'encoder_transformer_positional_encoding': True,
 'encoder_transformer_scale_embeddings': True,
 'encoder_type': 'lstm',
 'input_auto_model': [None],
 'input_auto_path': [None],
 'input_bert_path': ['bert-base-cased'],
 'input_dropout_rate': None,
 'input_elmo_path': [None],
 'input_embeddings_size': [768],
 'input_embeddings_tokenize_model': [None],
 'input_linear_size': None,
 'input_resize': [None],
 'input_word_dropout_rate': None}
Number of parameters (total): 147.92M
Number of parameters (learned): 39.61M
Warming up on 10 batches
Loading training and development data
Preprocessing training and development data
Shuffling training data
Ensemble 0 - Epoch 0 - Batch 0 - Sample 0 - Total Batch 0 - Total Sample 0 - Skipped 0 batch - Train losses = [None] - Dev losses = [None] - Dev wsd = [None] - Dev bleu = None
Traceback (most recent call last):
File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/train.py", line 101, in
main()
File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/train.py", line 97, in main
trainer.train()
File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/trainer.py", line 250, in train
dev_losses, dev_wsd, dev_bleu = self.test_on_dev(dev_samples, model)
File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/trainer.py", line 329, in test_on_dev
loss = self.get_loss_metrics(dev_samples, model)
File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/trainer.py", line 341, in get_loss_metrics
batch_x, batch_y, batch_z, batch_tt, actual_batch_size, reached_eof = read_batch_from_samples(dev_samples, self.batch_size, self.token_per_batch, current_index, model.config.data_config.input_features, model.config.data_config.output_features, model.config.data_config.output_translations, model.config.data_config.output_translation_features, model.config.data_config.input_clear_text, model.config.data_config.output_translation_clear_text)
File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/common.py", line 235, in read_batch_from_samples
pad_batch_y(batch_y)
File "/home/wangyangtao/ensimag/NLP/disambiguate/python/getalp/wsd/common.py", line 163, in pad_batch_y
batch_y[i] = pad_sequence(batch_y[i], batch_first=True)
File "/usr/lib/python3.7/site-packages/torch/nn/utils/rnn.py", line 376, in pad_sequence
max_size = sequences[0].size()
IndexError: list index out of range

**Comment by loic-vial** [comment]
Oh I see, this is because you did not specify a development corpus when launching the `prepare_data` script. You have to either specify the `--dev [corpus]` argument, which uses a specific corpus for the dev, or the `--dev_from_train [N]` argument, which extracts N lines from the train and use it for the dev.

I agree that the error is really not understandable though. I will update the code so there is an error in the `prepare_data` if the dev is empty.

**Comment by yassiridhbi** [comment]
> 
> 
> Oh I see, this is because you did not specify a development corpus when launching the `prepare_data` script. You have to either specify the `--dev [corpus]` argument, which uses a specific corpus for the dev, or the `--dev_from_train [N]` argument, which extracts N lines from the train and use it for the dev.
> 
> I agree that the error is really not understandable though. I will update the code so there is an error in the `prepare_data` if the dev is empty.

after doing all these steps, the training process freezed just before finishing, is that normal?

**Comment by schwabdidier** [comment]
@yassiridhbi please, address another issue
