### ISSUE TITLE
Replication of the reported results.

### ISSUE THREAD

**Issue by YixingLuan** [getalp/disambiguate#18]
Hello,
I'd like to replicate the reported results in "Sense Vocabulary Compression through the Semantic Knowledge of WordNet for Neural Word Sense Disambiguation (GWC19)", and I tried the pre-trained model you've provided (model_wsd_train_sc_wngt_dev_random4000_clear_compress_bert_large_cased_transformer_2048). However, I'm getting lower results than the reported results for "SemCor+WNGC, hypernyms". 
I ran the system as: 
`./evaluate.sh --data_path model_wsd_train_sc_wngt_dev_random4000_clear_compress_bert_la
rge_cased_transformer_2048 --weights model_wsd_train_sc_wngt_dev_random4000_clear_compress_bert_large_cased_transformer_204
8/model_weights_wsd0 --corpus ../UFSAC/corpus/ufsac-public-2.1/raganato_ALL.xml`

And I got the following:
`Arguments:
    --help (default value) = false
    --python_path = ./python
    --data_path = model_wsd_train_sc_wngt_dev_random4000_clear_compress_bert_large_cased_transformer_2048
    --weights = [model_wsd_train_sc_wngt_dev_random4000_clear_compress_bert_large_cased_transformer_2048/model_weights_wsd0]
    --corpus = [../UFSAC/corpus/ufsac-public-2.1/raganato_ALL.xml]
    --lowercase (default value) = false
    --sense_compression_hypernyms (default value) = true
    --sense_compression_instance_hypernyms (default value) = false
    --sense_compression_antonyms (default value) = false
    --sense_compression_file (default value) =
    --filter_lemma (default value) = true
    --clear_text (default value) = false
    --batch_size (default value) = 1

------ Evaluate the score of an ensemble of models

Evaluate on corpus ../UFSAC/corpus/ufsac-public-2.1/raganato_ALL.xml
Evaluate without backoff
(senseval2.d000) [76.09] (senseval2.d001) [80.33] (senseval2.d002) [78.19] (senseval3.d000) [74.02] (senseval3.d001) [72.13] (senseval3.d002) [79.93] (semeval2007.d000) [70.27] (semeval2007.d001) [69.33] (semeval2007.d002) [69.07] (semeval2013.d000) [81.65] (semeval2013.d001) [77.63] (semeval2013.d002) [67.65] (semeval2013.d003) [77.06] (semeval2013.d004) [71.70] (semeval2013.d005) [87.37] (semeval2013.d006) [68.54] (semeval2013.d007) [85.93] (semeval2013.d008) [77.99] (semeval2013.d009) [76.81] (semeval2013.d010) [71.52] (semeval2013.d011) [75.88] (semeval2013.d012) [85.57] (semeval2015.d000) [83.61] (semeval2015.d001) [68.65] (semeval2015.d002) [83.85] (semeval2015.d003) [83.05] ; good/bad/missed/total : 5595/1645/13/7253 ; C/P/R/F1 : 99.8208/77.2790/77.1405/77.2097 ; [n] good/bad/missed/total : 3454/841/5/4300 ; [n] C/P/R/F1 : 99.8837/80.4191/80.3256/80.3723 ; [v] good/bad/missed/total : 1077/575/0/1652 ; [v] C/P/R/F1 : 100.0000/65.1937/65.1937/65.1937 ; [a] good/bad/missed/total : 769/178/8/955 ; [a] C/P/R/F1 : 99.1623/81.2038/80.5236/80.8623 ; [r] good/bad/missed/total : 295/51/0/346 ; [r] C/P/R/F1 : 100.0000/85.2601/85.2601/85.2601 ; [x] good/bad/missed/total : 0/0/0/0 ; [x] C/P/R/F1 : NaN/NaN/NaN/NaN ; time : 69.445 seconds
Evaluate with monosemics
(senseval2.d000) [76.37] (senseval2.d001) [80.33] (senseval2.d002) [78.37] (senseval3.d000) [74.02] (senseval3.d001) [72.24] (senseval3.d002) [80.04] (semeval2007.d000) [70.27] (semeval2007.d001) [69.33] (semeval2007.d002) [69.07] (semeval2013.d000) [81.65] (semeval2013.d001) [77.63] (semeval2013.d002) [69.57] (semeval2013.d003) [77.06] (semeval2013.d004) [71.70] (semeval2013.d005) [87.37] (semeval2013.d006) [68.54] (semeval2013.d007) [85.93] (semeval2013.d008) [77.99] (semeval2013.d009) [76.81] (semeval2013.d010) [71.52] (semeval2013.d011) [75.88] (semeval2013.d012) [85.57] (semeval2015.d000) [83.78] (semeval2015.d001) [68.65] (semeval2015.d002) [83.85] (semeval2015.d003) [83.05] ; good/bad/missed/total : 5605/1645/3/7253 ; C/P/R/F1 : 99.9586/77.3103/77.2784/77.2944 ; [n] good/bad/missed/total : 3457/841/2/4300 ; [n] C/P/R/F1 : 99.9535/80.4328/80.3953/80.4140 ; [v] good/bad/missed/total : 1077/575/0/1652 ; [v] C/P/R/F1 : 100.0000/65.1937/65.1937/65.1937 ; [a] good/bad/missed/total : 776/178/1/955 ; [a] C/P/R/F1 : 99.8953/81.3417/81.2565/81.2991 ; [r] good/bad/missed/total : 295/51/0/346 ; [r] C/P/R/F1 : 100.0000/85.2601/85.2601/85.2601 ; [x] good/bad/missed/total : 0/0/0/0 ; [x] C/P/R/F1 : NaN/NaN/NaN/NaN ; time : 0.03 seconds
Evaluate with backoff first sense
(senseval2.d000) [76.32] (senseval2.d001) [80.33] (senseval2.d002) [78.37] (senseval3.d000) [74.02] (senseval3.d001) [72.24] (senseval3.d002) [80.04] (semeval2007.d000) [70.27] (semeval2007.d001) [69.33] (semeval2007.d002) [69.07] (semeval2013.d000) [81.44] (semeval2013.d001) [77.63] (semeval2013.d002) [69.57] (semeval2013.d003) [77.06] (semeval2013.d004) [71.70] (semeval2013.d005) [87.37] (semeval2013.d006) [68.54] (semeval2013.d007) [85.93] (semeval2013.d008) [77.99] (semeval2013.d009) [76.81] (semeval2013.d010) [71.05] (semeval2013.d011) [75.88] (semeval2013.d012) [85.57] (semeval2015.d000) [83.78] (semeval2015.d001) [68.65] (semeval2015.d002) [83.85] (semeval2015.d003) [83.05] ; good/bad/missed/total : 5605/1648/0/7253 ; C/P/R/F1 : 100.0000/77.2784/77.2784/77.2784 ; [n] good/bad/missed/total : 3457/843/0/4300 ; [n] C/P/R/F1 : 100.0000/80.3953/80.3953/80.3953 ; [v] good/bad/missed/total : 1077/575/0/1652 ; [v] C/P/R/F1 : 100.0000/65.1937/65.1937/65.1937 ; [a] good/bad/missed/total : 776/179/0/955 ; [a] C/P/R/F1 : 100.0000/81.2565/81.2565/81.2565 ; [r] good/bad/missed/total : 295/51/0/346 ; [r] C/P/R/F1 : 100.0000/85.2601/85.2601/85.2601 ; [x] good/bad/missed/total : 0/0/0/0 ; [x] C/P/R/F1 : NaN/NaN/NaN/NaN ; time : 0.023 seconds

------ Evaluate the scores of individual models

Evaluate on corpus ../UFSAC/corpus/ufsac-public-2.1/raganato_ALL.xml
0 Evaluate without backoff
(senseval2.d000) [76.09] (senseval2.d001) [80.33] (senseval2.d002) [78.19] (senseval3.d000) [74.02] (senseval3.d001) [72.13] (senseval3.d002) [79.93] (semeval2007.d000) [70.27] (semeval2007.d001) [69.33] (semeval2007.d002) [69.07] (semeval2013.d000) [81.65] (semeval2013.d001) [77.63] (semeval2013.d002) [67.65] (semeval2013.d003) [77.06] (semeval2013.d004) [71.70] (semeval2013.d005) [87.37] (semeval2013.d006) [68.54] (semeval2013.d007) [85.93] (semeval2013.d008) [77.99] (semeval2013.d009) [76.81] (semeval2013.d010) [71.52] (semeval2013.d011) [75.88] (semeval2013.d012) [85.57] (semeval2015.d000) [83.61] (semeval2015.d001) [68.65] (semeval2015.d002) [83.85] (semeval2015.d003) [83.05] ; good/bad/missed/total : 5595/1645/13/7253 ; C/P/R/F1 : 99.8208/77.2790/77.1405/77.2097 ; [n] good/bad/missed/total : 3454/841/5/4300 ; [n] C/P/R/F1 : 99.8837/80.4191/80.3256/80.3723 ; [v] good/bad/missed/total : 1077/575/0/1652 ; [v] C/P/R/F1 : 100.0000/65.1937/65.1937/65.1937 ; [a] good/bad/missed/total : 769/178/8/955 ; [a] C/P/R/F1 : 99.1623/81.2038/80.5236/80.8623 ; [r] good/bad/missed/total : 295/51/0/346 ; [r] C/P/R/F1 : 100.0000/85.2601/85.2601/85.2601 ; [x] good/bad/missed/total : 0/0/0/0 ; [x] C/P/R/F1 : NaN/NaN/NaN/NaN ; time : 70.149 seconds
0 Evaluate with monosemics
(senseval2.d000) [76.37] (senseval2.d001) [80.33] (senseval2.d002) [78.37] (senseval3.d000) [74.02] (senseval3.d001) [72.24] (senseval3.d002) [80.04] (semeval2007.d000) [70.27] (semeval2007.d001) [69.33] (semeval2007.d002) [69.07] (semeval2013.d000) [81.65] (semeval2013.d001) [77.63] (semeval2013.d002) [69.57] (semeval2013.d003) [77.06] (semeval2013.d004) [71.70] (semeval2013.d005) [87.37] (semeval2013.d006) [68.54] (semeval2013.d007) [85.93] (semeval2013.d008) [77.99] (semeval2013.d009) [76.81] (semeval2013.d010) [71.52] (semeval2013.d011) [75.88] (semeval2013.d012) [85.57] (semeval2015.d000) [83.78] (semeval2015.d001) [68.65] (semeval2015.d002) [83.85] (semeval2015.d003) [83.05] ; good/bad/missed/total : 5605/1645/3/7253 ; C/P/R/F1 : 99.9586/77.3103/77.2784/77.2944 ; [n] good/bad/missed/total : 3457/841/2/4300 ; [n] C/P/R/F1 : 99.9535/80.4328/80.3953/80.4140 ; [v] good/bad/missed/total : 1077/575/0/1652 ; [v] C/P/R/F1 : 100.0000/65.1937/65.1937/65.1937 ; [a] good/bad/missed/total : 776/178/1/955 ; [a] C/P/R/F1 : 99.8953/81.3417/81.2565/81.2991 ; [r] good/bad/missed/total : 295/51/0/346 ; [r] C/P/R/F1 : 100.0000/85.2601/85.2601/85.2601 ; [x] good/bad/missed/total : 0/0/0/0 ; [x] C/P/R/F1 : NaN/NaN/NaN/NaN ; time : 0.031 seconds
0 Evaluate with backoff first sense
(senseval2.d000) [76.32] (senseval2.d001) [80.33] (senseval2.d002) [78.37] (senseval3.d000) [74.02] (senseval3.d001) [72.24] (senseval3.d002) [80.04] (semeval2007.d000) [70.27] (semeval2007.d001) [69.33] (semeval2007.d002) [69.07] (semeval2013.d000) [81.44] (semeval2013.d001) [77.63] (semeval2013.d002) [69.57] (semeval2013.d003) [77.06] (semeval2013.d004) [71.70] (semeval2013.d005) [87.37] (semeval2013.d006) [68.54] (semeval2013.d007) [85.93] (semeval2013.d008) [77.99] (semeval2013.d009) [76.81] (semeval2013.d010) [71.05] (semeval2013.d011) [75.88] (semeval2013.d012) [85.57] (semeval2015.d000) [83.78] (semeval2015.d001) [68.65] (semeval2015.d002) [83.85] (semeval2015.d003) [83.05] ; good/bad/missed/total : 5605/1648/0/7253 ; C/P/R/F1 : 100.0000/77.2784/77.2784/77.2784 ; [n] good/bad/missed/total : 3457/843/0/4300 ; [n] C/P/R/F1 : 100.0000/80.3953/80.3953/80.3953 ; [v] good/bad/missed/total : 1077/575/0/1652 ; [v] C/P/R/F1 : 100.0000/65.1937/65.1937/65.1937 ; [a] good/bad/missed/total : 776/179/0/955 ; [a] C/P/R/F1 : 100.0000/81.2565/81.2565/81.2565 ; [r] good/bad/missed/total : 295/51/0/346 ; [r] C/P/R/F1 : 100.0000/85.2601/85.2601/85.2601 ; [x] good/bad/missed/total : 0/0/0/0 ; [x] C/P/R/F1 : NaN/NaN/NaN/NaN ; time : 0.019 seconds

Mean of scores without backoff: 77.2096874353136
Standard deviation without backoff: 0.0
Mean of scores with monosemics: 77.294352892505
Standard deviation with monosemics: 0.0
Mean of scores with backoff first sense: 77.27836757203916
Standard deviation with backoff first sense: 0.0`

This is lower than the reported results for "ALL" (79.0%). 
Could you give me some advice on that?

Thank you.

**Comment by loic-vial** [comment]
Hello, thank you for your interest in our work !

The pre-trained model that we provide and that you used is a "single model", not an "ensemble model", that's why you are having ~77% F1, this is what we obtain without ensembles in our paper (Table 5, second line).

We are uploading the other 7 models that we used to have our "ensemble" scores, today, so you can reproduce the results !

I will keep you informed on the upload, it may take a lot of time (I am not in the laboratory, because of the coronavirus :))

**Comment by loic-vial** [comment]
Hello again,
The upload is complete, we updated the README to include a link to the Ensemble model.

Here is the URL : https://zenodo.org/record/3759301

Please try it, you should have the expected results :)

**Comment by YixingLuan** [comment]
Thank you so much for the quick response.

I tried with the ensemble model, but I got "RuntimeError: CUDA out of memory" error because the GPU memory is not enough to handle the ensemble of 8 models. The GPU situation is shown below. 

Since my GPU could handle ensemble of 6 models, I ran the system with model_weights 0 - 5. However, the results are still around 77% for raganato_ALL.xml. 

Also, the paper says "we trained 8 independent models, and we give the score obtained by an ensemble system that averages their predictions through a geometric mean". Since my GPU cannot afford running the ensemble of 8 models at the same time, I tried running the system with each model_weight separately and afterwards computed the geometric mean of the score produced as the output ("Mean of scores with backoff first sense" of the each run). However, the geometric mean also becomes around 77% because each model_weight produces (76.9%-77.3%). 

I might misunderstand something.
Could you please give me some advice on this?

Thank you so much for your time.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN RTX           Off  | 00000000:65:00.0 Off |                  N/A |
| 37%   49C    P0    60W / 280W |      0MiB / 24217MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN RTX           Off  | 00000000:B3:00.0 Off |                  N/A |
| 32%   37C    P0    23W / 280W |      0MiB / 24220MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by loic-vial** [comment]
Yes, in fact, each individual model obtains an average score of ~77%, this is why we give mean score (77.08%) and standard deviation (+/- 0.17) in the table 5 of our paper. 

The "ensemble" technique is different. Like we said in the paper, it consists of "averaging the **predictions** [of individual models] through a geometric mean", this is not the same as "averaging the **scores** of individual models".

"Ensemble" or "model ensembling" is a technique that we first saw in the Machine Translation domain, for instance, here: https://arxiv.org/pdf/1409.3215.pdf or here: https://arxiv.org/pdf/1609.08144.pdf, but this is used in many other works on neural networks !

In our case, to be precise, each model first outputs a probability distribution over all senses in the output vocabulary, then we average each prediction of every sense of every model through a geometric mean, and finally we output the sense which has the maximum score.

If you want to see the code, this is the function "predict_ensemble_wsd_on_batch" in the file "predicter.py". If I remember correctly our code, instead of directly computing the probability distribution through softmax and then computing the geometric mean, we compute the **exponential of the arithmetic mean of the logarithm of the softmax** because this is computationnaly less expensive, but this is mathematically the same :)

Also, about the GPU memory, we had the same space issue as you, so we ran the "ensemble" experiments on CPU.

**Comment by loic-vial** [comment]
Oh and last thing, when you use the "evaluate.sh" script, it gives the "ensemble" scores in the first part, and then the "average" scores in the second part, so if you look again your output when you used 6 models, you should see the part "Evaluate the score of an ensemble of models" and it should be better than 77%

**Comment by loic-vial** [comment]
Also, by looking at "ensemble method" on google I found this figure which is a nice illustration of the process : https://www.researchgate.net/figure/llustration-of-ensemble-methods-An-illustrative-example-of-all-four-ensemble-methods_fig1_324898558

**Comment by YixingLuan** [comment]
Thank you so much for your detailed explanation.
I misunderstood that the averaged score produced at the end is the ensemble model's performance.
Following your advice, I ran the ensemble model on CPU and could replicate the results reported in the paper. Thank you so much.

Now, in addition to the model performance, I'd like to obtain the ensemble model's sense predictions accompanied by probabilities. As you mentioned in your response, it seems that the function "predict_ensemble_wsd_on_batch" is computing the probabilities. However, when I edited the "predicter.py" to output predictions, some errors occurred in Java side:
`[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project disambiguate: An exception occured while executing the Java class. java.lang.NumberFormatException: For input string: "predict_wsd_on_batch" -> [Help 1]                                                                                                              org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project disambiguate: An exception occured while executing the Java class. java.lang.NumberFormatException: For input string: "predict_wsd_on_batch"`

Does your code have any function, which allows me to obtain system's predictions?
If doesn't, is there any simple way to achieve that?

Thank you so much for your help.

**Comment by loic-vial** [comment]
Simple answer: no there is not a function or a simple way to get the system's probabilities...

More complete answer:
The code is structured as followed: when you run "decode.sh" for instance, it calls first the Java main class "NeuralWSDDecode" which takes care of lemmatizing/pos-tagging the input, and then it calls the Python script "predict.py" with a specific format in input, and expects a specific format in output (see methods writePredictInput(...) and readPredictOutput(...) from class NeuralDisambiguator).  

This is why you cannot change the Python "predicter" outputs without changing also the Java methods.

So I see two solutions :
1) (clean, complex) Modify the Python and Java codes to optionnally ask for probabilities and take them into account when parsing the output, but this can be a bit complex because there is a lot of classes in Java to manipulate...
2) (dirty, easier) Bypass the mechanism by writing to a file (or stderr, but not stdout because it will be read by the Java code) the probabilities that you want, so the Java doesn't read it, but you can still get it.

I personnaly don't have the time currently to do those changes, but I hope you'll be able to get what you want :) Good luck !

**Comment by YixingLuan** [comment]
Hello,
Following your advice, I could finally obtain the predictions from the source code. 
Also, using the hypernyms_mapping.txt and the obtained predictions, I could replicate the reported results as well.

Thank you so much for your help.
I'm closing this issue.
